### ISSUE TITLE
Privat menupont

### ISSUE THREAD

**Issue by benelori** [benelori/beci#5]
Create Homepage content with blocks and newest blog entries, and ask about the target audience of the site and decide on content based on that.

Create blocks to invite new members

Private: not main menu item(depends on layout), but separate block and/or page
1. Contact List - no excel, internal drupal content type and views (suggest just create/edit(?) and no delete for regular users)
2. See Members page entry and #4
3. Talk and suggest something visual (cover page and link to pdf)
4. Separate content type? 
5. Separate Content Type? Just file?
6. Regular admin interface(perhaps individual link)

**Comment by benelori** [comment]
1es megvan.

**Comment by benelori** [comment]
Mi a kulonbseg a 2es es a 6os kozott?

**Comment by benelori** [comment]
Iparag elemzesek es esettanulmanyok tobb info

**Comment by benelori** [comment]
Videok azok FB-hoz kotodnek, vagy privat videok?

**Comment by beci8811** [comment]
Privat videok, semmi koze a facebookhoz.

**Comment by beci8811** [comment]
Ide pdfeket es pptker fogunk feltolteni
